import { APISymbol } from '../types';

const symbologyArr: APISymbol[] = [
  {
    english: 'tap this permanent',
    gatherer_alternates: ['ocT', 'oT'],
    symbol: '{T}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/T.svg',
  },
  {
    english: 'untap this permanent',
    symbol: '{Q}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/Q.svg',
  },
  {
    english: 'an energy counter',
    symbol: '{E}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/E.svg',
  },
  {
    english: 'planeswalker',
    symbol: '{PW}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/PW.svg',
  },
  {
    english: 'chaos',
    symbol: '{CHAOS}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/CHAOS.svg',
  },
  {
    english: 'an acorn counter',
    funny: true,
    symbol: '{A}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/A.svg',
  },
  {
    english: 'a ticket counter',
    symbol: '{TK}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/TK.svg',
  },
  {
    appears_in_mana_costs: true,
    english: 'X generic mana',
    gatherer_alternates: ['oX', 'ooX'],
    loose_variant: 'X',
    represents_mana: true,
    symbol: '{X}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/X.svg',
  },
  {
    appears_in_mana_costs: true,
    english: 'Y generic mana',
    funny: true,
    loose_variant: 'Y',
    represents_mana: true,
    symbol: '{Y}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/Y.svg',
  },
  {
    appears_in_mana_costs: true,
    english: 'Z generic mana',
    funny: true,
    loose_variant: 'Z',
    represents_mana: true,
    symbol: '{Z}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/Z.svg',
  },
  {
    appears_in_mana_costs: true,
    english: 'zero mana',
    gatherer_alternates: ['o0'],
    loose_variant: '0',
    represents_mana: true,
    symbol: '{0}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/0.svg',
  },
  {
    cmc: 0.5,
    english: 'one-half generic mana',
    funny: true,
    gatherer_alternates: ['o½'],
    loose_variant: '½',
    represents_mana: true,
    symbol: '{½}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/HALF.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    english: 'one generic mana',
    gatherer_alternates: ['o1'],
    loose_variant: '1',
    represents_mana: true,
    symbol: '{1}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/1.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 2,
    english: 'two generic mana',
    gatherer_alternates: ['o2'],
    loose_variant: '2',
    represents_mana: true,
    symbol: '{2}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/2.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 3,
    english: 'three generic mana',
    gatherer_alternates: ['o3'],
    loose_variant: '3',
    represents_mana: true,
    symbol: '{3}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/3.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 4,
    english: 'four generic mana',
    gatherer_alternates: ['o4'],
    loose_variant: '4',
    represents_mana: true,
    symbol: '{4}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/4.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 5,
    english: 'five generic mana',
    gatherer_alternates: ['o5'],
    loose_variant: '5',
    represents_mana: true,
    symbol: '{5}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/5.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 6,
    english: 'six generic mana',
    gatherer_alternates: ['o6'],
    loose_variant: '6',
    represents_mana: true,
    symbol: '{6}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/6.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 7,
    english: 'seven generic mana',
    gatherer_alternates: ['o7'],
    loose_variant: '7',
    represents_mana: true,
    symbol: '{7}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/7.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 8,
    english: 'eight generic mana',
    gatherer_alternates: ['o8'],
    loose_variant: '8',
    represents_mana: true,
    symbol: '{8}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/8.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 9,
    english: 'nine generic mana',
    gatherer_alternates: ['o9'],
    loose_variant: '9',
    represents_mana: true,
    symbol: '{9}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/9.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 10,
    english: 'ten generic mana',
    gatherer_alternates: ['o10'],
    loose_variant: '10',
    represents_mana: true,
    symbol: '{10}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/10.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 11,
    english: 'eleven generic mana',
    gatherer_alternates: ['o11'],
    loose_variant: '11',
    represents_mana: true,
    symbol: '{11}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/11.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 12,
    english: 'twelve generic mana',
    gatherer_alternates: ['o12'],
    loose_variant: '12',
    represents_mana: true,
    symbol: '{12}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/12.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 13,
    english: 'thirteen generic mana',
    gatherer_alternates: ['o13'],
    loose_variant: '13',
    represents_mana: true,
    symbol: '{13}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/13.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 14,
    english: 'fourteen generic mana',
    gatherer_alternates: ['o14'],
    loose_variant: '14',
    represents_mana: true,
    symbol: '{14}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/14.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 15,
    english: 'fifteen generic mana',
    gatherer_alternates: ['o15'],
    loose_variant: '15',
    represents_mana: true,
    symbol: '{15}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/15.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 16,
    english: 'sixteen generic mana',
    gatherer_alternates: ['o16'],
    loose_variant: '16',
    represents_mana: true,
    symbol: '{16}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/16.svg',
  },
  {
    cmc: 17,
    english: 'seventeen generic mana',
    gatherer_alternates: ['o17'],
    loose_variant: '17',
    represents_mana: true,
    symbol: '{17}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/17.svg',
  },
  {
    cmc: 18,
    english: 'eighteen generic mana',
    gatherer_alternates: ['o18'],
    loose_variant: '18',
    represents_mana: true,
    symbol: '{18}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/18.svg',
  },
  {
    cmc: 19,
    english: 'nineteen generic mana',
    gatherer_alternates: ['o19'],
    loose_variant: '19',
    represents_mana: true,
    symbol: '{19}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/19.svg',
  },
  {
    cmc: 20,
    english: 'twenty generic mana',
    gatherer_alternates: ['o20'],
    loose_variant: '20',
    represents_mana: true,
    symbol: '{20}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/20.svg',
  },
  {
    cmc: 100,
    english: 'one hundred generic mana',
    funny: true,
    loose_variant: '100',
    represents_mana: true,
    symbol: '{100}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/100.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1000000,
    english: 'one million generic mana',
    funny: true,
    loose_variant: '1000000',
    represents_mana: true,
    symbol: '{1000000}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/1000000.svg',
  },
  {
    cmc: Infinity,
    english: 'infinite generic mana',
    funny: true,
    loose_variant: '∞',
    represents_mana: true,
    symbol: '{∞}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/INFINITY.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['W', 'U'],
    english: 'one white or blue mana',
    represents_mana: true,
    symbol: '{W/U}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/WU.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['W', 'B'],
    english: 'one white or black mana',
    represents_mana: true,
    symbol: '{W/B}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/WB.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['B', 'R'],
    english: 'one black or red mana',
    represents_mana: true,
    symbol: '{B/R}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/BR.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['B', 'G'],
    english: 'one black or green mana',
    represents_mana: true,
    symbol: '{B/G}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/BG.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['U', 'B'],
    english: 'one blue or black mana',
    represents_mana: true,
    symbol: '{U/B}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/UB.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['U', 'R'],
    english: 'one blue or red mana',
    represents_mana: true,
    symbol: '{U/R}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/UR.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['R', 'G'],
    english: 'one red or green mana',
    represents_mana: true,
    symbol: '{R/G}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/RG.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['W', 'R'],
    english: 'one red or white mana',
    represents_mana: true,
    symbol: '{R/W}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/RW.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['W', 'G'],
    english: 'one green or white mana',
    represents_mana: true,
    symbol: '{G/W}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/GW.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['U', 'G'],
    english: 'one green or blue mana',
    represents_mana: true,
    symbol: '{G/U}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/GU.svg',
    transposable: true,
  },
  {
    cmc: 1,
    colors: ['B', 'G'],
    english: 'one black mana, one green mana, or 2 life',
    represents_mana: true,
    symbol: '{B/G/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/BGP.svg',
    transposable: true,
  },
  {
    cmc: 1,
    colors: ['B', 'R'],
    english: 'one black mana, one red mana, or 2 life',
    represents_mana: true,
    symbol: '{B/R/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/BRP.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['U', 'G'],
    english: 'one green mana, one blue mana, or 2 life',
    represents_mana: true,
    symbol: '{G/U/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/GUP.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['W', 'G'],
    english: 'one green mana, one white mana, or 2 life',
    represents_mana: true,
    symbol: '{G/W/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/GWP.svg',
    transposable: true,
  },
  {
    cmc: 1,
    colors: ['R', 'G'],
    english: 'one red mana, one green mana, or 2 life',
    represents_mana: true,
    symbol: '{R/G/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/RGP.svg',
    transposable: true,
  },
  {
    cmc: 1,
    colors: ['W', 'R'],
    english: 'one red mana, one white mana, or 2 life',
    represents_mana: true,
    symbol: '{R/W/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/RWP.svg',
    transposable: true,
  },
  {
    cmc: 1,
    colors: ['U', 'B'],
    english: 'one blue mana, one black mana, or 2 life',
    represents_mana: true,
    symbol: '{U/B/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/UBP.svg',
    transposable: true,
  },
  {
    cmc: 1,
    colors: ['U', 'R'],
    english: 'one blue mana, one red mana, or 2 life',
    represents_mana: true,
    symbol: '{U/R/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/URP.svg',
    transposable: true,
  },
  {
    cmc: 1,
    colors: ['W', 'B'],
    english: 'one white mana, one black mana, or 2 life',
    represents_mana: true,
    symbol: '{W/B/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/WBP.svg',
    transposable: true,
  },
  {
    cmc: 1,
    colors: ['W', 'U'],
    english: 'one white mana, one blue mana, or 2 life',
    represents_mana: true,
    symbol: '{W/U/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/WUP.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 2,
    colors: ['W'],
    english: 'two generic mana or one white mana',
    represents_mana: true,
    symbol: '{2/W}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/2W.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 2,
    colors: ['U'],
    english: 'two generic mana or one blue mana',
    represents_mana: true,
    symbol: '{2/U}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/2U.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 2,
    colors: ['B'],
    english: 'two generic mana or one black mana',
    represents_mana: true,
    symbol: '{2/B}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/2B.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 2,
    colors: ['R'],
    english: 'two generic mana or one red mana',
    represents_mana: true,
    symbol: '{2/R}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/2R.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 2,
    colors: ['G'],
    english: 'two generic mana or one green mana',
    represents_mana: true,
    symbol: '{2/G}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/2G.svg',
    transposable: true,
  },
  {
    cmc: 1,
    english: 'one colored mana or two life',
    represents_mana: true,
    symbol: '{P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/P.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['W'],
    english: 'one white mana or two life',
    represents_mana: true,
    symbol: '{W/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/WP.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['U'],
    english: 'one blue mana or two life',
    represents_mana: true,
    symbol: '{U/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/UP.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['B'],
    english: 'one black mana or two life',
    represents_mana: true,
    symbol: '{B/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/BP.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['R'],
    english: 'one red mana or two life',
    represents_mana: true,
    symbol: '{R/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/RP.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['G'],
    english: 'one green mana or two life',
    represents_mana: true,
    symbol: '{G/P}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/GP.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 0.5,
    colors: ['W'],
    english: 'one-half white mana',
    funny: true,
    represents_mana: true,
    symbol: '{HW}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/HW.svg',
    transposable: true,
  },
  {
    cmc: 0.5,
    colors: ['R'],
    english: 'one-half red mana',
    funny: true,
    represents_mana: true,
    symbol: '{HR}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/HR.svg',
    transposable: true,
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['W'],
    english: 'one white mana',
    gatherer_alternates: ['oW', 'ooW'],
    loose_variant: 'W',
    represents_mana: true,
    symbol: '{W}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/W.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['U'],
    english: 'one blue mana',
    gatherer_alternates: ['oU', 'ooU'],
    loose_variant: 'U',
    represents_mana: true,
    symbol: '{U}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/U.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['B'],
    english: 'one black mana',
    gatherer_alternates: ['oB', 'ooB'],
    loose_variant: 'B',
    represents_mana: true,
    symbol: '{B}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/B.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['R'],
    english: 'one red mana',
    gatherer_alternates: ['oR', 'ooR'],
    loose_variant: 'R',
    represents_mana: true,
    symbol: '{R}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/R.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    colors: ['G'],
    english: 'one green mana',
    gatherer_alternates: ['oG', 'ooG'],
    loose_variant: 'G',
    represents_mana: true,
    symbol: '{G}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/G.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    english: 'one colorless mana',
    loose_variant: 'C',
    represents_mana: true,
    symbol: '{C}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/C.svg',
  },
  {
    appears_in_mana_costs: true,
    cmc: 1,
    english: 'one snow mana',
    loose_variant: 'S',
    represents_mana: true,
    symbol: '{S}',
    svg_uri: 'https://svgs.scryfall.io/card-symbols/S.svg',
  },
];

export const symbologyMap = Object.fromEntries(
  symbologyArr.map((symbol) => [symbol.symbol, symbol]),
);
